import type { Metadata } from "next";

export const siteConfig = {
  name: "İngiltere Vize Randevu",
  url: "https://ukvizebasvuru.com",
  whatsapp: "https://wa.me/905531229372",
  phone: "+90 553 122 93 72",
  email: "destek@ukvizebasvuru.com",
};

export function pageMetadata(title: string, description: string, path: string): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: `${siteConfig.url}${path}`,
      siteName: siteConfig.name,
      locale: "tr_TR",
      type: "website",
    },
  };
}

export const navigation = [
  { href: "/", label: "Ana Sayfa" },
  { href: "/hakkimizda", label: "Hakkımızda" },
  { href: "/ucretler", label: "Ücretler" },
  { href: "/vfs-rehberi", label: "VFS Rehberi" },
  { href: "/uk-vize-merkezleri", label: "Vize Merkezleri" },
  { href: "/blog", label: "Blog" },
  { href: "/sss", label: "SSS" },
  { href: "/iletisim", label: "İletişim" },
];

export const processSteps = [
  "Doğru vize türünün belirlenmesi",
  "Online başvuru hazırlığı",
  "İngiltere vize ücret planlaması",
  "VFS randevu organizasyonu",
  "Destekleyici belge hazırlığı",
  "PDF ve belge yükleme optimizasyonu",
  "Başvuru takibi",
  "Pasaport teslim süreci",
];

export const govFees = [
  { category: "Standart Ziyaretçi Vizesi - 6 ay", fee: "$190" },
  { category: "Standart Ziyaretçi Vizesi - 2 yıl", fee: "$713" },
  { category: "Standart Ziyaretçi Vizesi - 5 yıl", fee: "$1273" },
  { category: "Standart Ziyaretçi Vizesi - 10 yıl", fee: "$1590" },
  { category: "DATV Transit Vizesi", fee: "$59" },
  { category: "Transit Ziyaretçi Vizesi", fee: "$105" },
  { category: "Kısa Dönem Öğrenci Vizesi", fee: "$321" },
  { category: "Ebeveyn Vizesi", fee: "$1023" },
];

export const consultancyFees = [
  { package: "Tek Başvuru Sahibi", gbp: "£115", tl: "6.750 TL" },
  { package: "2 Başvuru Sahibi", gbp: "£100 / kişi", tl: "6.000 TL / kişi" },
  { package: "Aile Başvurusu - Yetişkin 1", gbp: "-", tl: "6.000 TL" },
  { package: "Aile Başvurusu - Yetişkin 2", gbp: "-", tl: "6.000 TL" },
  { package: "Aile Başvurusu - 18 Yaş Altı", gbp: "-", tl: "3.000 TL / çocuk" },
];

export const faqItems = [
  {
    q: "İngiltere vize randevu nasıl alınır?",
    a: "Doğru vize türünü seçtikten sonra online form doldurulur, ücret ödenir ve VFS biyometri randevusu oluşturulur.",
  },
  {
    q: "İngiltere vizesi kaç günde çıkar?",
    a: "Yoğunluğa göre değişebilir. Ortalama süreler başvuru tipine ve döneme göre farklılaşır.",
  },
  {
    q: "VFS randevusu nasıl alınır?",
    a: "Form ve ödeme adımları tamamlandıktan sonra VFS sisteminden uygun tarih-saat seçilerek alınır.",
  },
  {
    q: "Bankada ne kadar para olmalı?",
    a: "Sabit bir rakam yoktur. Seyahat planı, gelir-gider dengesi ve finansal sürdürülebilirlik birlikte değerlendirilir.",
  },
  {
    q: "Sponsorlu başvuru yapılabilir mi?",
    a: "Evet. Sponsorun finansal belgeleri ve başvuru sahibiyle ilişkisini destekleyen evraklarla yapılabilir.",
  },
  {
    q: "Çok girişli vize nasıl alınır?",
    a: "Seyahat geçmişi, gerekçe ve finansal profilin doğru yapılandırılmasıyla çok girişli uzun süreli ziyaretçi vizelerine başvurulabilir.",
  },
  {
    q: "Uçak bileti gerekli mi?",
    a: "Kesin satın alım zorunlu değildir. Ancak tutarlı bir seyahat planı ve rezervasyon mantığı önemlidir.",
  },
  {
    q: "Vize reddi durumunda ne olur?",
    a: "Ret gerekçesi analiz edilerek dosya revize edilir, yeni strateji ile yeniden başvuru hazırlanır.",
  },
];

export const centers = [
  { city: "İstanbul", hours: "08:00 – 18:00" },
  { city: "Ankara", hours: "09:00 – 17:00" },
  { city: "Antalya", hours: "09:00 – 17:00" },
  { city: "İzmir", hours: "09:00 – 17:00" },
  { city: "Adana", hours: "09:00 – 17:00" },
  { city: "Bursa", hours: "09:00 – 17:00" },
  { city: "Gaziantep", hours: "09:00 – 17:00" },
  { city: "Trabzon", hours: "09:00 – 17:00" },
  { city: "Altunizade", hours: "09:00 – 17:00" },
];

export const blogPosts = [
  {
    slug: "ingiltere-vize-basvurusu",
    title: "İngiltere Vize Başvurusu: Adım Adım Süreç Yönetimi",
    excerpt: "Başvurudan pasaport teslimine kadar süreç akışı.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-01-10",
    readingTime: "8 dk okuma",
  },
  {
    slug: "ingiltere-vize-evraklari",
    title: "İngiltere Vize Evrakları: Tam Kontrol Listesi",
    excerpt: "Başvuru dosyanızı eksiksiz hale getiren evrak mimarisi.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-01-17",
    readingTime: "7 dk okuma",
  },
  {
    slug: "ingiltere-vize-ucreti-2026",
    title: "İngiltere Vize Ücreti 2026 Rehberi",
    excerpt: "Güncel UKVI ücretleri ve danışmanlık ücret ayrımı.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-02-03",
    readingTime: "6 dk okuma",
  },
  {
    slug: "ingiltere-turist-vizesi",
    title: "İngiltere Turist Vizesi Dosya Stratejisi",
    excerpt: "Turist vizesi dosyasında finansal ve operasyonel doğruluk.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-02-14",
    readingTime: "8 dk okuma",
  },
  {
    slug: "ingiltere-business-visa",
    title: "İngiltere Ticari Ziyaret Vizesi Başvurusu",
    excerpt: "Şirket sahipleri ve iş seyahati için belge yapısı.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-02-21",
    readingTime: "7 dk okuma",
  },
  {
    slug: "ingiltere-vize-randevusu",
    title: "İngiltere Vize Randevusu Planlama Kılavuzu",
    excerpt: "VFS randevu planlama, evrak eşleşmesi ve tarih optimizasyonu.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-03-01",
    readingTime: "7 dk okuma",
  },
  {
    slug: "vfs-upload-nasil-yapilir",
    title: "VFS Belge Yükleme Nasıl Yapılır?",
    excerpt: "PDF hazırlığı, isimlendirme ve belge eşleştirme.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-03-08",
    readingTime: "6 dk okuma",
  },
  {
    slug: "ingiltere-vize-red-nedenleri",
    title: "İngiltere Vize Red Nedenleri",
    excerpt: "Sık ret nedenleri ve önleyici başvuru stratejileri.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-03-15",
    readingTime: "9 dk okuma",
  },
  {
    slug: "bank-statement-nasil-hazirlanir",
    title: "Banka Hesap Dökümü Nasıl Hazırlanır?",
    excerpt: "Hesap hareketlerinin finansal anlatım gücünü artırma.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-03-22",
    readingTime: "8 dk okuma",
  },
  {
    slug: "sponsorlu-basvuru-rehberi",
    title: "Sponsorlu Başvuru Rehberi",
    excerpt: "Sponsor evrakları ve ilişki ispat düzeni.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-04-05",
    readingTime: "8 dk okuma",
  },
  {
    slug: "sirket-sahipleri-icin-ingiltere-vizesi",
    title: "Şirket Sahipleri için İngiltere Vizesi",
    excerpt: "Ticari faaliyet belgeleriyle güçlü dosya kurgusu.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-04-12",
    readingTime: "9 dk okuma",
  },
  {
    slug: "pdf-dosya-isimlendirme-rehberi",
    title: "PDF Dosya İsimlendirme Rehberi",
    excerpt: "VFS yüklemede düzenli klasör ve dosya standartları.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-04-19",
    readingTime: "6 dk okuma",
  },
  {
    slug: "ingiltere-vizesi-kac-gunde-cikar",
    title: "İngiltere Vizesi Kaç Günde Çıkar?",
    excerpt: "Süreleri etkileyen değişkenler ve planlama önerileri.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-05-03",
    readingTime: "7 dk okuma",
  },
  {
    slug: "ingiltere-vizesi-icin-hesapta-ne-kadar-para-olmali",
    title: "İngiltere Vizesi için Hesapta Ne Kadar Para Olmalı?",
    excerpt: "Finansal yeterlilikte tek rakam değil tutarlılık esastır.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-05-10",
    readingTime: "8 dk okuma",
  },
  {
    slug: "ingiltere-multiple-entry-vizesi",
    title: "İngiltere Çok Girişli Vizesi",
    excerpt: "Çok girişli vize için seyahat profili ve belge stratejisi.",
    category: "Destek Rehberi",
    date: "2026-05-17",
    readingTime: "8 dk okuma",
  },
  // TIER S — MAX CONVERSION
  {
    slug: "ingiltere-vize-basvurusu-nasil-yapilir",
    title: "İngiltere Vize Başvurusu Nasıl Yapılır? (2026 Güncel Rehber)",
    excerpt: "İngiltere vize başvurusunda doğru adımlar, evrak düzeni ve süreç yönetimi.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-06-01",
    readingTime: "10 dk okuma",
  },
  {
    slug: "ingiltere-vizesi-icin-gerekli-evraklar",
    title: "İngiltere Vizesi İçin Gerekli Evraklar (2026 Tam Liste)",
    excerpt: "Başvuru dosyanızı eksiksiz hazırlamak için tüm evrak listesi ve checklist.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-06-08",
    readingTime: "9 dk okuma",
  },
  {
    slug: "vfs-global-belge-yukleme-nasil-yapilir",
    title: "VFS Global Belge Yükleme Nasıl Yapılır?",
    excerpt: "VFS sistemi üzerinden belge yükleme adımları, PDF hazırlığı ve yaygın hatalar.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-06-15",
    readingTime: "7 dk okuma",
  },
  {
    slug: "ingiltere-vize-randevusu-nasil-alinir",
    title: "İngiltere Vize Randevusu Nasıl Alınır?",
    excerpt: "VFS randevu sistemi üzerinden adım adım randevu alma rehberi.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-06-22",
    readingTime: "7 dk okuma",
  },
  // TIER A — HIGH AUTHORITY
  {
    slug: "ingiltere-vizesi-icin-bankada-ne-kadar-para-olmali",
    title: "İngiltere Vizesi İçin Bankada Ne Kadar Para Olmalı?",
    excerpt: "UKVI'nin beklediği finansal yeterlilik düzeyi ve banka hesabı hazırlığı.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-07-05",
    readingTime: "8 dk okuma",
  },
  {
    slug: "sponsorlu-ingiltere-vizesi-rehberi",
    title: "Sponsorlu İngiltere Vizesi Rehberi",
    excerpt: "Sponsor ilişkisi, destekleyici evraklar ve dosya kurgusu.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-07-12",
    readingTime: "9 dk okuma",
  },
  {
    slug: "ingiltere-vizesi-cover-letter-ornegi",
    title: "İngiltere Vizesi İçin Niyet Mektubu Nasıl Yazılır?",
    excerpt: "Niyet mektubu yapısı, içerik stratejisi ve dikkat edilmesi gereken noktalar.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-07-19",
    readingTime: "8 dk okuma",
  },
  {
    slug: "ingiltere-multiple-entry-vize",
    title: "İngiltere Çok Girişli Vizesi Nasıl Alınır?",
    excerpt: "Çok girişli vize için seyahat geçmişi, profil kurgusu ve başvuru stratejisi.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-08-02",
    readingTime: "8 dk okuma",
  },
  // TIER B — TOPICAL AUTHORITY
  {
    slug: "gov-uk-uzerinden-ingiltere-vize-basvurusu",
    title: "GOV.UK Üzerinden İngiltere Vize Başvurusu",
    excerpt: "Resmi portal üzerinden başvuru akışı, form doldurma ve ödeme adımları.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-08-09",
    readingTime: "7 dk okuma",
  },
  {
    slug: "ingiltere-vize-basvuru-formu",
    title: "İngiltere Vize Başvuru Formu Nasıl Doldurulur?",
    excerpt: "Online başvuru formunda dikkat edilmesi gereken kritik alanlar.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-08-16",
    readingTime: "7 dk okuma",
  },
  {
    slug: "ingiltere-turist-vizesi-rehberi",
    title: "İngiltere Turist Vizesi Rehberi",
    excerpt: "Turist vizesi için gereken belgeler, finansal yeterlilik ve başvuru stratejisi.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-09-06",
    readingTime: "8 dk okuma",
  },
  {
    slug: "vfs-randevu-gunu",
    title: "VFS Randevu Günü Ne Olur?",
    excerpt: "Randevu günü hazırlığı, biyometrik işlemler ve dikkat edilmesi gerekenler.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-09-13",
    readingTime: "6 dk okuma",
  },
  // HIGH INTENT GOLD URLs
  {
    slug: "ingiltere-vize-danismanlik",
    title: "İngiltere Vize Danışmanlığı: Profesyonel Destek ile Başvuru",
    excerpt: "Uzman danışmanlık hizmetiyle dosya kurgusu, evrak hazırlığı ve randevu sürecini doğru yönetin.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-09-20",
    readingTime: "8 dk okuma",
  },
  {
    slug: "ingiltere-vize-randevu-ucreti",
    title: "İngiltere Vize Randevu Ücreti 2026",
    excerpt: "UKVI başvuru ücreti, VFS hizmet bedeli ve toplam maliyet planlaması için güncel rehber.",
    category: "Ana Hizmet Sayfası",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-09-27",
    readingTime: "6 dk okuma",
  },
  {
    slug: "ingiltere-vizesi-kolay-alinir-mi",
    title: "İngiltere Vizesi Kolay Alınır mı?",
    excerpt: "Vize onay oranını etkileyen faktörler, yaygın hatalar ve başarı şansını artıran dosya stratejisi.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-10-04",
    readingTime: "7 dk okuma",
  },
  {
    slug: "ingiltere-vizesi-reddi-itiraz",
    title: "İngiltere Vizesi Reddine İtiraz Süreci",
    excerpt: "Red kararının analizi, Administrative Review başvurusu ve yeniden başvuru stratejisi.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-10-11",
    readingTime: "9 dk okuma",
  },
  {
    slug: "vfs-randevu-bulma",
    title: "VFS Randevu Bulma: Uygun Tarih Nasıl Bulunur?",
    excerpt: "Yoğun dönemlerde VFS randevu takibi, erken tarih stratejileri ve alternatif merkez seçenekleri.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-10-18",
    readingTime: "6 dk okuma",
  },
  {
    slug: "ingiltere-vize-basvurusu-kac-gunde-sonuclanir",
    title: "İngiltere Vize Başvurusu Kaç Günde Sonuçlanır?",
    excerpt: "Standart ve öncelikli işlem süreleri, yoğunluk dönemleri ve sonuç takip yöntemleri.",
    category: "Destek Rehberi",
    author: "UK Vize Danışmanlık Ekibi",
    date: "2026-10-25",
    readingTime: "7 dk okuma",
  },
];

export const coreLinks = [
  "/ucretler",
  "/vfs-global-randevu",
  "/sss",
  "/iletisim",
  "/blog",
];
